### ISSUE TITLE
[wallet] 리액트

### ISSUE THREAD

**Issue by repedore** [codestates/BTC2nd-08#8]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [ ] 니모닉으로 시드 생성
2. [ ] 리액트에서 크롬 익스텐션 storage 사용 기능 구현
3. [ ] 로그인시 실제 테스트넷에서 사용 가능한 지갑인지 확인
4. [ ] 테스트넷 코인 받기
5. [ ] 니모닉으로 계정 복구

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1day`
- Group : `client`
- Sprint: `Sprint__1__`
- Urgency: `Middle`
